name: aim

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # Use the same version as your local environment

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Inject Firebase configuration
        run: node public/build.js

      - name: Deploy to Netlify
        uses: netlify/actions/cli@main
        with:
          args: deploy --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          SHARED_SECRET: ${{ secrets.SHARED_SECRET }}
