[build]
  command = "npm ci"
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://maywopselmp.github.io"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, x-session-id"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self' https://earnest-treacle-eded95.netlify.app https://www.gstatic.com https://www.googleapis.com; script-src 'self' https://www.gstatic.com; style-src 'self'; connect-src 'self' https://www.googleapis.com https://your-firebase-project.firebaseio.com https://earnest-treacle-eded95.netlify.app; object-src 'none'; form-action 'self';"
